---
- hosts: prod
  tasks:
  - name: Upload src app
    copy: src=src/time dest=/home/ec2-user/app

  - name: Upload Dockerfile
    copy: src=Dockerfile dest=/home/ec2-user/Dockerfile mode=0755

  - name: Deploy Docker container
    become_user: ec2-user
    script: deploy.sh